# Generated by Django 6.0.2 on 2026-02-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='generated_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
