# Generated by Django 6.0.2 on 2026-02-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_chunk_generated_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='generated_notes',
        ),
        migrations.AddField(
            model_name='note',
            name='generated_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
