# Generated by Django 6.0.2 on 2026-02-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_complete',
        ),
    ]
